// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hxmuesfqnrrbvzcngpud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4bXVlc2ZxbnJyYnZ6Y25ncHVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5NzUxOTIsImV4cCI6MjA1ODU1MTE5Mn0.JIFoIZ4K3LpcrNglN0r5dNlhX79wLFYA_ueaVhiAjkA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);